steps:
  build:
    when:
      event: [push, pull_request]
    image: ubuntu:latest
    commands:
      - apt-get update
      - apt-get -y install libmad0-dev libid3tag0-dev libsndfile1-dev libgd-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev wget cmake gcc g++
      - wget https://github.com/google/googletest/archive/release-1.12.1.tar.gz
      - tar xzf release-1.12.1.tar.gz
      - ln -s googletest-release-1.12.1 googletest
      - mkdir build
      - cd build
      - cmake ..
      - make
      - ./audiowaveform --version
      - ./audiowaveform_tests
